version: '3.5'

services:

  spark-worker:
    image: ghcr.io/osekoo/spark:$spark_version$
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
    deploy:
      replicas: \${SPARK_WORKERS:-2}
    depends_on:
      - $name;format="normalize"$-spark-master

